### ISSUE TITLE
Where's my gradient @?

### ISSUE THREAD

**Issue by jud3bl4nk** [jud3bl4nk/ecommerce-pattern-library#3]
Hello again,
I created a gradient in cards.css for milk-drop-bg.html and am trying to apply it to the html file as a background, but the gradient is not appearing. I've checked the gradient in other locations, and it doesn't work so I assume I made a semantic error in the gradient CSS but can't find it... help?
Thanks,
Jude
@mackenzierose

**Comment by MacKenzieRose** [comment]
@jud3bl4nk 

Not a problem; can you commit/push your code so I can see the new changes you've made?

**Comment by jud3bl4nk** [comment]
Hey, Done! Sorry that took a while.

**Comment by MacKenzieRose** [comment]
In cards.css:

Change the "background color" to "background"
     You should see the gradient work on your Item info card now.


Then, in milk-drop-bg.html, I'm going to take the the formatting of the card from your item-info.html, but in general, we want to avoid using classes like "island" outside of a "grid." 

<img width="607" alt="Screen Shot 2020-02-04 at 1 10 03 PM" src="https://user-images.githubusercontent.com/19557909/73773189-b2719c80-474f-11ea-9fa0-57bd28913f51.png">


Let me know how that works for you :)

**Comment by jud3bl4nk** [comment]
Hey, it's working. Thank you!
