### ISSUE TITLE
Problem with filter btns

### ISSUE THREAD

**Issue by jud3bl4nk** [jud3bl4nk/ecommerce-pattern-library#5]
Hi @mackenzierose and @missmadore !
Hope you're doing well.
The problem is as follows...
I have a type of filter (patters/navigation/filters.html) set up for my main page. The filter is made up of btns, each with a section which is supposed to appear below it when the btn is activated, disapear when the btn is clicked twice, and switch out for the selected section if another btn is clicked.  I am only a humble graphic designer/multi media artist and I am unable to use my big but obstinate brain to make any of those actions happen. There are many reasons this could be; if you believe in God you could blaim him, personally I blaim my poor genetics. Regardless, I hope that you are able to find a solution to my problem.
Best, 
Jude
P.S I am getting bored in captivity

**Comment by MissMadore** [comment]
https://www.w3schools.com/howto/howto_js_filter_elements.asp 

Check this walkthrough out, my main concern is that you're calling a filterSelection() function but I don't see anywhere in your js files that actually defines that function. As my javascript is still a little shakey, I'd recommend that you get @thomasjbradley to look at it quickly to troubleshoot. 

Good luck! Sorry I can't be of more help, I'm not as good at debugging if I can't see someone's functioning code in front of me

**Comment by thomasjbradley** [comment]
With this small change, we can make most of the functionality work:
https://github.com/jud3bl4nk/ecommerce-pattern-library/blob/master/_patterns/buttons/honey-btn.html#L3

```html
<a class="btn image-btn" href="#honey">
```

1. Delete the `{{include.button_text}}`
2. Add `#honey` into the `href`

The only thing that’s missing is a second click to close. And for that, we definitely need JavaScript.

**Comment by MacKenzieRose** [comment]
If this issue has been resolved, feel free to close it :)

Cheers!
MacKenzie
