### ISSUE TITLE
Grades for Assignments

### ISSUE THREAD

**Issue by MacKenzieRose** [jud3bl4nk/ecommerce-pattern-library#7]
Hi @thomasjbradley

Jude and I have been working on their pattern library, and we've gotten quite a bit done, so I wanted to put together an update for you. Also, in learning how to create pull requests, I realize I tried to change the master assignment code, so my apologies for that!

1) The responsive banner assignment is marked with an "X" on Jude's progress site, but given that this was a Markbot assignment, I'm not fully sure why this would be. We've run into issues in the past with Jude's Markbot giving the cheating type errors often reserved for changing the yml files, but all this to say, we'd love to be able to submit this assignment at some point if possible.

2) Today we worked through browser and accessibility testing together, so I'm of the opinion that the **Informal Accessibility Testing** & **Informal Browser Testing** have been sufficiently completed. Neither of us have access to Android phones, so no mobile android testing was conducted. However, Firefox, Chrome, Safari, Edge, and Opera were explored on desktops, while mobile was limited to iPhones. In general, we found that some text backgrounds weren't coloured the same as local host, which affected readability. We also consistently had problems with the main banner's responsiveness across browser scales, and frequently had images that refused to load. This site is very image heavy, so at slower connections, it was painful. Some gradients also appeared to be saved as background images, which browsers reported as broken images. With the accessibility testing, the lack of skip links and ARIA was sorely felt in terms of functionality, but the inclusion of alt tags and general site flow was still reasonable. 

Overall, I think we identified many problems with the site, but it is unlikely that all of these will be addressed by the end of the semester. However, in the context of the assignment, I'm confident that Jude understands how to test sites, and document issues therein.

3) I think Jude has done a reasonable job addressing the **Navigations & Sections, Headers & Footers**, and **Sharing code with layouts** assignments; if you disagree, let us know what further work should be completed and we'll address it. 

Thanks so much for your time. Hope you're having a great weekend.

Cheers!

MacKenzie (& Jude)

**Comment by thomasjbradley** [comment]
1. I’ve opened “responsive-banner” for resubmission—so try again.

2. Checked off.

3. I’m unable to see the website because there’s no Netlify URL attached to the repository.
